<?
$env = (getenv('APP_ENV') == 'development') ? true : false;
$title = $this->getHelperPluginManager()->getServiceLocator()->get('config')['siteTitle'];
$copyright = $this->getHelperPluginManager()->getServiceLocator()->get('config')['siteCopyright'];
echo $this->doctype();
?>
<html lang="en" ng-app="BlurAdmin">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <base href="<?=$this->basePath('/'); ?>">
    <?=$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>
    
    <?=$this->headTitle($title)->setSeparator(' | ')->setAutoEscape(false) ?>

    <link rel="icon" type="image/png" sizes="16x16" href="<?=$this->basePath('/img/favicon-16x16.png'); ?>">
    <link rel="icon" type="image/png" sizes="32x32" href="<?=$this->basePath('/img/favicon-32x32.png'); ?>">
    <link rel="icon" type="image/png" sizes="96x96" href="<?=$this->basePath('/img/favicon-96x96.png'); ?>">
    <link rel="icon" type="image/png" sizes="128x128" href="<?=$this->basePath('/img/favicon-128x128.png'); ?>">
    
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900italic,900&subset=latin,greek,greek-ext,vietnamese,cyrillic-ext,latin-ext,cyrillic' rel='stylesheet' type='text/css'>
    
    <? foreach ($this->getCssCollection() as $css) $this->headLink()->appendStylesheet($this->basePath($css)); ?>
    <?=$this->headLink(); ?>
    
</head>
<body>
<div class="body-bg"></div>
<main ng-if="$pageFinishedLoading" ng-class="{ 'menu-collapsed': $baSidebarService.isMenuCollapsed() }">

    <ba-sidebar></ba-sidebar>
    <page-top></page-top>

    <?=$this->content; ?>

    <footer class="al-footer clearfix">
        <div class="al-footer-main clearfix">
            <div class="al-copy"><strong>Copyright</strong> &copy; <?=$this->siteYear() . ' ' . $copyright; ?></div>
        </div>
    </footer>

    <back-top></back-top>
</main>

<div id="preloader" ng-show="!$pageFinishedLoading">
    <div></div>
</div>
<ng-image-gallery
    images="gallery.images"
    methods="gallery.methods"
    thumbnails="false"
    bg-close="true"
></ng-image-gallery>
<?=$this->inlineScript() ?>

<? foreach ($this->getJsCollection() as $js) $this->headScript()->prependFile($this->basePath($js)); ?>
<?=$this->headScript(); ?>
</body>
</html>